<a href="https://colab.research.google.com/github/Sebory/Tensorflow/blob/main/Exercise01/exercise01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Iintialization of Tensor

In [29]:
import tensorflow as tf

In [30]:
print(tf.__version__)

2.9.2


In [31]:
x = tf.constant(4, shape=(1, 1), dtype=tf.float32)
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [32]:
y = tf.constant([[1,2,3],[4,5,6]])
print(y)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [33]:
z = tf.ones((3,3))
print(z)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [34]:
e = tf.eye(4)
print(e)

tf.Tensor(
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]], shape=(4, 4), dtype=float32)


In [35]:
a = tf.random.normal((3,3), mean=0, stddev=1)
print(a)

tf.Tensor(
[[-1.6399813  -0.12367767  1.4821497 ]
 [-1.1246718   0.63825274 -0.78244734]
 [-0.74895114  0.06249755 -1.1505741 ]], shape=(3, 3), dtype=float32)


In [36]:
b = tf.range(9)
print(b)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [37]:
c = tf.range(start=1, limit=10, delta=2)
print(c)

tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)


# Mathematical Operations

In [40]:
x = tf.constant([1,2,3])
y = tf.constant([9,8,7])
z = tf.add(x, y)
print(z)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [41]:
z = tf.tensordot(x, y, axes=1)
print(z)

tf.Tensor(46, shape=(), dtype=int32)


In [42]:
z = tf.reduce_sum(x*y, axis=0)
print(z)

tf.Tensor(46, shape=(), dtype=int32)


In [44]:
x = tf.random.normal((2,3))
y = tf.random.normal((3,4))
z = tf.matmul(x, y)
print(z)
z = x @ y
print(z)

tf.Tensor(
[[-2.2383654   0.01734436 -1.001091   -2.3638675 ]
 [-2.423493   -1.1910819   0.71476936 -0.08751321]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[-2.2383654   0.01734436 -1.001091   -2.3638675 ]
 [-2.423493   -1.1910819   0.71476936 -0.08751321]], shape=(2, 4), dtype=float32)


# Indexing

In [52]:
x = tf.constant([0,1,1,2,3,1,2,3])
print(x[:])
print(x[1:])
print(x[1:3])
print(x[::2])
# to print in the reverse order
print(x[::-1])

tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)
tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([1 1], shape=(2,), dtype=int32)
tf.Tensor([0 1 3 2], shape=(4,), dtype=int32)
tf.Tensor([3 2 1 3 2 1 1 0], shape=(8,), dtype=int32)


In [54]:
x = tf.constant([0,1,7,9,8,8,2,3])
# let extract some indices of x just above
indices = tf.constant([0,3])
x_ind = tf.gather(x, indices)
print(x_ind)

tf.Tensor([0 9], shape=(2,), dtype=int32)


In [58]:
x = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])
print(x[0,:])
print(x[:2,:])

tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [63]:
x = tf.range(9)
print(x)

x = tf.reshape(x, (3,3))
print(x)

x = tf.transpose(x, perm=[1,0])
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
